package com.me.crm.mapper;

import com.me.crm.entity.SaleChance;

public interface SaleChanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    int insert(SaleChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    int insertSelective(SaleChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    SaleChance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SaleChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaleChance record);
}