package com.me.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.sn
     *
     * @mbggenerated
     */
    private String sn;
    
    private Date createTime;
    
    private Date updateTime;
    
    private List<Permission> permissionList = new ArrayList<>();
    
    public Role() {
    	super();
    }
    
    public Role(Integer id, String name, String sn, Date createTime, Date updateTime) {
        this.id = id;
        this.name = name;
        this.sn = sn;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }
    
    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	public String getSn() {
		return sn;
	}

	public void setSn(String sn) {
		this.sn = sn == null ? null : sn.trim();
	}
	
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Override
	public String toString() {
		return "Role [id=" + id + ", name=" + name + ", sn=" + sn + ", permissionList=" + permissionList + "]";
	}
}