package com.me.crm.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class SaleChance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.chance_source
     *
     * @mbggenerated
     */
    private String chanceSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.success_rate
     *
     * @mbggenerated
     */
    private Integer successRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.create_man
     *
     * @mbggenerated
     */
    private String createMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.dev_result
     *
     * @mbggenerated
     */
    private Integer devResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd hh:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.update_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd hh:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    public SaleChance(Integer id, String chanceSource, Integer customerId, Integer productId, Integer userId, Integer successRate, String description, String createMan, Integer status, Integer devResult, Date createTime, Date updateTime) {
        this.id = id;
        this.chanceSource = chanceSource;
        this.customerId = customerId;
        this.productId = productId;
        this.userId = userId;
        this.successRate = successRate;
        this.description = description;
        this.createMan = createMan;
        this.status = status;
        this.devResult = devResult;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    public SaleChance() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.id
     *
     * @return the value of sale_chance.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.id
     *
     * @param id the value for sale_chance.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.chance_source
     *
     * @return the value of sale_chance.chance_source
     *
     * @mbggenerated
     */
    public String getChanceSource() {
        return chanceSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.chance_source
     *
     * @param chanceSource the value for sale_chance.chance_source
     *
     * @mbggenerated
     */
    public void setChanceSource(String chanceSource) {
        this.chanceSource = chanceSource == null ? null : chanceSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.customer_id
     *
     * @return the value of sale_chance.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.customer_id
     *
     * @param customerId the value for sale_chance.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.product_id
     *
     * @return the value of sale_chance.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.product_id
     *
     * @param productId the value for sale_chance.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.user_id
     *
     * @return the value of sale_chance.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.user_id
     *
     * @param userId the value for sale_chance.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.success_rate
     *
     * @return the value of sale_chance.success_rate
     *
     * @mbggenerated
     */
    public Integer getSuccessRate() {
        return successRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.success_rate
     *
     * @param successRate the value for sale_chance.success_rate
     *
     * @mbggenerated
     */
    public void setSuccessRate(Integer successRate) {
        this.successRate = successRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.description
     *
     * @return the value of sale_chance.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.description
     *
     * @param description the value for sale_chance.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.create_man
     *
     * @return the value of sale_chance.create_man
     *
     * @mbggenerated
     */
    public String getCreateMan() {
        return createMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.create_man
     *
     * @param createMan the value for sale_chance.create_man
     *
     * @mbggenerated
     */
    public void setCreateMan(String createMan) {
        this.createMan = createMan == null ? null : createMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.status
     *
     * @return the value of sale_chance.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.status
     *
     * @param status the value for sale_chance.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.dev_result
     *
     * @return the value of sale_chance.dev_result
     *
     * @mbggenerated
     */
    public Integer getDevResult() {
        return devResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.dev_result
     *
     * @param devResult the value for sale_chance.dev_result
     *
     * @mbggenerated
     */
    public void setDevResult(Integer devResult) {
        this.devResult = devResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.create_time
     *
     * @return the value of sale_chance.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm:ss" , timezone = "GMT+08")
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.create_time
     *
     * @param createTime the value for sale_chance.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.update_time
     *
     * @return the value of sale_chance.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd hh:mm:ss" , timezone = "GMT+08")
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.update_time
     *
     * @param updateTime the value for sale_chance.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", chanceSource=").append(chanceSource);
        sb.append(", customerId=").append(customerId);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", successRate=").append(successRate);
        sb.append(", description=").append(description);
        sb.append(", createMan=").append(createMan);
        sb.append(", status=").append(status);
        sb.append(", devResult=").append(devResult);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}